# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "128"
  end

  config.ssh.insert_key = false

  config.vm.define "server", primary: true do |server|
    server.vm.hostname = "server"
    server.vm.box = "generic/alpine38"
    server.vm.network "private_network", ip: "10.92.3.1"
    server.vm.network "private_network", ip: "10.1.92.1"
    server.vm.network "public_network"  
    server.vm.provision "file", source: "dhcpd.conf", destination: "/tmp/"
    server.vm.provision "shell", inline: <<-SHELL
     echo "update apk"
     sudo apk update
     echo "install dhcp server"
     sudo apk add dhcp
     sudo cp /tmp/dhcpd.conf /etc/dhcp/
    SHELL
  end
  
  config.vm.define "client1" do |client1|
    client1.vm.hostname = "client1"
    client1.vm.box = "generic/alpine38"
    client1.vm.network "private_network", ip: "10.1.92.2", auto_config: false
    client1.vm.network "private_network", ip: "172.16.3.1"
  end

  config.vm.define "client2" do |client2|
    client2.vm.hostname = "client2"
    client2.vm.box = "generic/alpine38"
    client2.vm.network "private_network", ip: "10.92.3.2", auto_config: false
    client2.vm.network "private_network", ip: "172.16.3.2"
  end
end

