# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/alpine38"
  config.vm.network "private_network", ip: "10.92.3.1"
  config.vm.network "private_network", ip: "10.1.92.1"
  config.vm.network "public_network"
    config.vm.provider "virtualbox" do |vb|
      vb.memory = "128"
    end
end
